"""Legacy rebuild of the integrated article from the two historical sources.

``paper/combined_article.tex`` is now the canonical PRE manuscript and contains
editorial and robustness changes not represented in the historical split
sources.  To prevent accidental loss, this script is a no-op unless explicitly
called with ``--force-legacy``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"


def section_slice(text: str, start: str, stop: str | None = None) -> str:
    begin = text.index(start)
    end = text.index(stop, begin) if stop is not None else len(text)
    return text[begin:end].strip()


def namespace_model_labels(text: str) -> str:
    pattern = re.compile(r"\\(label|ref|eqref|pageref)\{([^{}]+)\}")

    def replace(match: re.Match[str]) -> str:
        command, label = match.groups()
        if label.startswith("model:"):
            return match.group(0)
        return rf"\{command}{{model:{label}}}"

    return pattern.sub(replace, text)


def main() -> None:
    if "--force-legacy" not in sys.argv[1:]:
        print(
            "No changes: paper/combined_article.tex is canonical. "
            "Use --force-legacy only to reconstruct the obsolete split-paper draft."
        )
        return
    measurement = (PAPER / "paper1_measurement.tex").read_text(encoding="utf-8")
    model = (PAPER / "paper2_model.tex").read_text(encoding="utf-8")

    measurement_body = section_slice(
        measurement, r"\section{Introduction}", r"\section{Discussion}"
    )
    measurement_body = measurement_body.replace(
        r"\ref{sec:discussion}", r"\ref{sec:integrated-discussion}"
    )
    measurement_body = measurement_body.replace(r"\cite{paper2}", r"\cite{code_keldysh_finance}")
    model_body = section_slice(
        model, r"\section{The action}", r"\section{Discussion}"
    )
    model_body = namespace_model_labels(model_body)
    model_body = model_body.replace(r"\cite{paper1}", r"\cite{code_keldysh_finance}")

    abstract = r"""\begin{abstract}
We develop and test a transport description of signed taker flow in liquid
cryptocurrency markets.  The empirical part measures response, noise, full
counting statistics, two-time relaxation, and daily modulation from four
publicly observable pairs over four years.  The transferred-flow variance is
superdiffusive, with exponent $1.10$--$1.43$ under estimators that remove
constant, linear, or quadratic mean drift, while the trade-size-normalised
Fano factor is $905$--$3342$ and grows with the counting window.  These
features are incompatible with the sub-Poissonian, diffusive counting sector
of a noninteracting fermionic conductor.  The second-order sector is closed
by the measured correlation function: its counting variance, response shape,
and linear fluctuation-symmetry slope require no additional parameters.  We
make this closure explicit by constructing the corresponding
Martin--Siggia--Rose--Janssen--De Dominicis action and deriving the
parameter-free relation $V_T\sim T^{2-a}$ for a correlation tail
$C(\tau)\sim\tau^{-a}$.  An exactly solved nonequilibrium Green-function
device reproduces an ageing mean with a non-ageing correlation, but remains
diffusive and sub-Poissonian.  The comparison localises the missing physics
in the combination of compound, heavy-tailed transfers and long memory,
while keeping the finer crossover of local exponents as an open empirical
test rather than an established claim.
\end{abstract}"""

    document = rf"""% Generated by tools/build_combined_article.py.
\documentclass[aps,pre,twocolumn,superscriptaddress,floatfix,nofootinbib]{{revtex4-2}}

\usepackage{{amsmath,amssymb,amsthm,bm}}
\usepackage{{graphicx}}
\usepackage[colorlinks=true,allcolors=blue]{{hyperref}}

\newcommand{{\eps}}{{\varepsilon}}
\newcommand{{\epst}}{{\tilde{{\eps}}}}
\newcommand{{\avg}}[1]{{\left\langle #1 \right\rangle}}
\newcommand{{\Teff}}{{T_{{\mathrm{{eff}}}}}}
\newcommand{{\Var}}{{\mathrm{{Var}}}}
\newcommand{{\dd}}{{\mathrm{{d}}}}
\newtheorem{{proposition}}{{Proposition}}
\newtheorem{{remark}}{{Remark}}

\begin{{document}}
\title{{Signed order flow as a transport current:\\
measurement, response-field theory, and the limits of free transport}}

\author{{Nelson Bol\'{{\i}}var}}
\affiliation{{Escuela de F\'{{\i}}sica, Facultad de Ciencias, Universidad Central de Venezuela, Caracas 1041-A, Venezuela}}
\affiliation{{Astrum Drive Technologies, 13024 Dallas Pkwy Unit 120 B, Frisco, TX 75034, USA}}
\author{{Gabriel Abell\'an}}
\affiliation{{Escuela de F\'{{\i}}sica, Facultad de Ciencias, Universidad Central de Venezuela, Caracas 1041-A, Venezuela}}
\affiliation{{Astrum Drive Technologies, 13024 Dallas Pkwy Unit 120 B, Frisco, TX 75034, USA}}
\author{{David Verrilli}}
\affiliation{{Escuela de F\'{{\i}}sica, Facultad de Ciencias, Universidad Central de Venezuela, Caracas 1041-A, Venezuela}}
\date{{\today}}

{abstract}
\maketitle

{measurement_body}

\section{{Response-field theory}}
\label{{sec:model}}
{model_body}

\section{{Integrated discussion}}
\label{{sec:integrated-discussion}}
The measurements and the model form one argument, but not one undifferentiated
claim.  The robust empirical statements are the superdiffusive counting
variance and the very large trade-size-normalised noise.  The response and
second-order counting closure are useful consistency checks: once the
correlation kernel is fixed, they carry little independent information.  The
response-field formulation makes this distinction precise and predicts the
variance exponent from an observable family different from the one in which it
is measured.

The exactly solved conductor supplies a calibrated negative result.  It can
produce a relaxing mean without ageing its correlation, but its counting
statistics remain sub-Poissonian and diffusive.  Thus the comparison does not
identify a unique microscopic market model.  It does, however, rule out the
idea that the observed bunching and superdiffusion can be obtained by tuning
an otherwise free-fermion bath.  A marked, interacting flow process with
long memory is the minimal direction left open by the data.

The local drift of the counting exponent is deliberately not promoted to a
discovery: the block estimator is sensitive to the measured drift of the
mean, while drift-blind estimators are not decisive at the longest windows.
Longer records or assets with a stationary mean flow are needed to separate
the two mechanisms.  This separation of established results, consistency
checks, and unresolved tests is the intended scope of the article.

\bibliographystyle{{apsrev4-2}}
\bibliography{{refs}}
\end{{document}}
"""
    target = PAPER / "combined_article.tex"
    target.write_text(document, encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main()
